"""Constants and lookup tables for CAMPS member data."""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"

MEMBER_FILE_CANDIDATES = [
    DATA_DIR / "members.csv",
    DATA_DIR / "members.xlsx",
    DATA_DIR / "Master Member List - 2026 Master List.csv",
]

STANDARD_COLUMNS = [
    "member_id",
    "member_name",
    "category",
    "industry",
    "membership_type",
    "website",
    "renewal",
    "renewal_month",
    "primary_contact",
    "job_title",
    "email",
    "phone",
    "address",
    "city",
    "zip",
    "county",
    "region",
    "size_band",
    "contact_count",
    "dba_names",
    "opted_out",
    "bounced",
    "has_website",
]

SECTION_MARKERS = {
    "MANUFACTURERS",
    "JOINT ACCESS - CANNABIS",
    "JOINT ACCESS - WINE ASSOCIATION",
    "JOINT ACCESS - BREWING",
    "JOINT ACCESS - PNAA",
    "JOINT ACCESS - NIMA",
    "SUPPLY CHAIN",
    "ASSOCIATES",
    "AFFILIATES",
}

MEMBERSHIP_TYPES = {"Health Trust", "Corporate Sponsor", "IN-KIND"}

INDUSTRY_MAP = {
    "MANUFACTURERS": "Manufacturing",
    "JOINT ACCESS - CANNABIS": "Cannabis",
    "JOINT ACCESS - WINE ASSOCIATION": "Wine",
    "JOINT ACCESS - BREWING": "Brewing",
    "JOINT ACCESS - PNAA": "Aerospace (PNAA)",
    "JOINT ACCESS - NIMA": "Maritime (NIMA)",
    "SUPPLY CHAIN": "Supply Chain",
    "ASSOCIATES": "Associate",
    "AFFILIATES": "Affiliate",
}

REGION_MAP = {
    "King": "Puget Sound",
    "Snohomish": "Puget Sound",
    "Pierce": "South Sound",
    "Kitsap": "South Sound",
    "Thurston": "South Sound",
    "Clark": "Southwest WA",
    "Cowlitz": "Southwest WA",
    "Skagit": "Northwest WA",
    "Whatcom": "Northwest WA",
    "Island": "Northwest WA",
    "San Juan": "Northwest WA",
    "Spokane": "Central/Eastern WA",
    "Yakima": "Central/Eastern WA",
    "Benton": "Central/Eastern WA",
    "Franklin": "Central/Eastern WA",
    "Walla Walla": "Central/Eastern WA",
    "Chelan": "Central/Eastern WA",
    "Douglas": "Central/Eastern WA",
    "Grant": "Central/Eastern WA",
    "Kittitas": "Central/Eastern WA",
    "Okanogan": "Central/Eastern WA",
    "Stevens": "Central/Eastern WA",
    "Whitman": "Central/Eastern WA",
    "Lewis": "Central/Eastern WA",
    "Mason": "South Sound",
    "Jefferson": "Northwest WA",
    "Clallam": "Northwest WA",
    "Grays Harbor": "Southwest WA",
    "Pacific": "Southwest WA",
    "Wahkiakum": "Southwest WA",
    "Klickitat": "Central/Eastern WA",
    "Adams": "Central/Eastern WA",
    "Asotin": "Central/Eastern WA",
    "Columbia": "Central/Eastern WA",
    "Ferry": "Central/Eastern WA",
    "Garfield": "Central/Eastern WA",
    "Lincoln": "Central/Eastern WA",
    "Pend Oreille": "Central/Eastern WA",
    "Skamania": "Southwest WA",
    "Out of State": "Out of State",
    "Unknown": "Unknown",
}

CITY_TO_COUNTY = {
    "seattle": "King",
    "bellevue": "King",
    "redmond": "King",
    "kirkland": "King",
    "renton": "King",
    "kent": "King",
    "auburn": "King",
    "federal way": "King",
    "issaquah": "King",
    "sammamish": "King",
    "bothell": "King",
    "shoreline": "King",
    "tukwila": "King",
    "woodinville": "King",
    "everett": "Snohomish",
    "mukilteo": "Snohomish",
    "lynnwood": "Snohomish",
    "edmonds": "Snohomish",
    "monroe": "Snohomish",
    "marysville": "Snohomish",
    "tacoma": "Pierce",
    "puyallup": "Pierce",
    "sumner": "Pierce",
    "lakewood": "Pierce",
    "fife": "Pierce",
    "olympia": "Thurston",
    "lacey": "Thurston",
    "bellingham": "Whatcom",
    "anacortes": "Skagit",
    "mount vernon": "Skagit",
    "burlington": "Skagit",
    "ferndale": "Whatcom",
    "spokane": "Spokane",
    "vancouver": "Clark",
    "yakima": "Yakima",
    "wenatchee": "Chelan",
    "walla walla": "Walla Walla",
    "kennewick": "Benton",
    "richland": "Benton",
    "pasco": "Franklin",
    "bainbridge island": "Kitsap",
    "bremerton": "Kitsap",
    "port orchard": "Kitsap",
    "silverdale": "Kitsap",
}

ZIP3_TO_COUNTY = {
    "980": "King",
    "981": "King",
    "982": "Snohomish",
    "983": "Pierce",
    "984": "Pierce",
    "985": "Thurston",
    "986": "Clark",
    "988": "Chelan",
    "989": "Yakima",
    "990": "Spokane",
    "991": "Spokane",
    "992": "Spokane",
    "993": "Benton",
}

MONTH_NAMES = {
    "january": 1,
    "february": 2,
    "march": 3,
    "april": 4,
    "may": 5,
    "june": 6,
    "july": 7,
    "august": 8,
    "september": 9,
    "october": 10,
    "november": 11,
    "december": 12,
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "apr": 4,
    "jun": 6,
    "jul": 7,
    "aug": 8,
    "sep": 9,
    "oct": 10,
    "nov": 11,
    "dec": 12,
}